services:
  zm.rideservice.api:
    image: ${DOCKER_REGISTRY-}zmrideserviceapi
    build:
      context: .
      dockerfile: ZM.RideService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - proxybackend

  zm.driverservice.api:
    image: ${DOCKER_REGISTRY-}zmdriverserviceapi
    build:
      context: .
      dockerfile: ZM.DriverService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5100
    ports:
      - "5100:5100"
      - "5101:5101"
    networks:
      - proxybackend

  zm.matchingservice.api:
    image: ${DOCKER_REGISTRY-}zmmatchingserviceapi
    build:
      context: .
      dockerfile: ZM.MatchingService.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5200
    ports:
      - "5200:5200"
      - "5201:5201"
    networks:
      - proxybackend

  mqbroker:
    image: rabbitmq:3-management
    container_name: MQueue
    hostname: distributedsys-mq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
      - mqvolume:/var/lib/rabbitmq
    networks: 
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge

volumes:
  mqvolume:
